version: "3.8"

services:
  frontend:
    build:
      context: .
    container_name: react_frontend_prod
    restart: always
    expose:
      - "80"  # expose port internally, not to host
    environment:
      - NODE_ENV=production

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"  # only Nginx exposes port 80 to host
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
