version: "3.8"

services:
  frontend:
    build:
      context: .
    container_name: frontend-app
    restart: always
    expose:
      - "80"
    environment:
      - NODE_ENV=production

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
