# Build Stage
FROM node:18 AS build

WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./
RUN npm install

# Copy the entire app and build it
COPY . .
COPY .env.production .env.production

# Build the project
RUN npm run build

# The rest is handled by the compose file