version: "3.8"

services:
  fastapi:
    build: .
    container_name: fastapi_app
    restart: always
    ports:
      - "8081:8000"
    env_file:
      - .env
    environment:
      SHOPIFY_ACCESS_TOKEN: ${SHOPIFY_ACCESS_TOKEN}
      SHOPIFY_API_URL: ${SHOPIFY_API_URL}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      FACEBOOK_PAGE_ACCESS_TOKEN: ${FACEBOOK_PAGE_ACCESS_TOKEN}
      FACEBOOK_VERIFY_TOKEN: ${FACEBOOK_VERIFY_TOKEN}
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
      GOOGLE_CSE_ID: ${GOOGLE_CSE_ID}

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - fastapi
