name: Deploy FastAPI to AWS Lightsail

on:
  push:
    branches:
      - master  # Trigger on push to master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up SSH Key
        run: |
          echo "${{ secrets.LIGHTSAIL_SSH_KEY }}" > lightsail_key.pem
          chmod 600 lightsail_key.pem  # Secure key permissions

      - name: Test SSH Connection
        run: |
          ssh -o StrictHostKeyChecking=no -i lightsail_key.pem ubuntu@${{ secrets.LIGHTSAIL_IP }} "echo '✅ SSH Connection Successful!'"

      - name: Deploy Application
        run: |
          ssh -o StrictHostKeyChecking=no -i lightsail_key.pem ubuntu@${{ secrets.LIGHTSAIL_IP }} << 'EOF'
            set -e  # Exit if any command fails

            # Go to home directory
            cd /home/ubuntu

            # Clone the repo if not already present
            if [ ! -d "ChatBotAI" ]; then
              git clone git@github.com:amangrwl30/ChatBotAI.git
            fi

            cd ChatBotAI/shopify

            # Pull latest code
            git pull origin master

            # Rebuild and restart the container
            docker-compose down
            docker-compose up -d --build
          EOF

      - name: Cleanup SSH Key
        if: always()
        run: rm -f lightsail_key.pem
