name: Deploy Frontend to AWS Lightsail

on:
  push:
    branches:
      - master
    paths:
      - 'frontend/**'
      - '.github/workflows/deploy-frontend.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up SSH Key
        run: |
          echo "${{ secrets.LIGHTSAIL_SSH_KEY }}" > lightsail_key.pem
          chmod 600 lightsail_key.pem

      - name: Test SSH Connection
        run: |
          ssh -o StrictHostKeyChecking=no -i lightsail_key.pem ubuntu@${{ secrets.LIGHTSAIL_IP }} "echo '✅ SSH Connection Successful!'"

      - name: Deploy Frontend & Nginx using Docker Compose
        run: |
          ssh -o StrictHostKeyChecking=no -i lightsail_key.pem ubuntu@${{ secrets.LIGHTSAIL_IP }} << 'EOF'
          set -e
          cd /home/ubuntu
          if [ ! -d "ChatBotAI" ]; then
            git clone https://github.com/amangrwl30/ChatBotAI.git
          fi
          cd ChatBotAI
          git pull origin master
          
          cd frontend
          docker compose down || true
          docker compose up -d --build
          EOF

      - name: Cleanup SSH Key
        if: always()
        run: rm -f lightsail_key.pem
