name: Deploy FastAPI to AWS Lightsail

on:
  push:
    branches:
      - master  # Trigger only on push to master
    paths:
      - 'Shopify/**'                          # Trigger only if files in Shopify folder change
      - '.github/workflows/deploy-backend.yml'  # Also trigger if this workflow file itself is updated

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up SSH Key
        run: |
          echo "${{ secrets.LIGHTSAIL_SSH_KEY }}" > lightsail_key.pem
          chmod 600 lightsail_key.pem

      - name: Test SSH Connection
        run: |
          ssh -o StrictHostKeyChecking=no -i lightsail_key.pem ubuntu@${{ secrets.LIGHTSAIL_IP }} "echo '✅ SSH Connection Successful!'"

      - name: Deploy Backend Application with Environment Variables
        run: |
          ssh -o StrictHostKeyChecking=no -i lightsail_key.pem ubuntu@${{ secrets.LIGHTSAIL_IP }} << 'EOF'
          set -e
          cd /home/ubuntu
          if [ ! -d "ChatBotAI" ]; then
            git clone https://github.com/amangrwl30/ChatBotAI.git
          fi
          cd ChatBotAI/Shopify
          git pull --rebase origin master
          cat > .env << 'EOT'
          OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
          SHOPIFY_API_URL=${{ secrets.SHOPIFY_API_URL }}
          SHOPIFY_ACCESS_TOKEN=${{ secrets.SHOPIFY_ACCESS_TOKEN }}
          FACEBOOK_PAGE_ACCESS_TOKEN=${{ secrets.FACEBOOK_PAGE_ACCESS_TOKEN }}
          FACEBOOK_VERIFY_TOKEN=${{ secrets.FACEBOOK_VERIFY_TOKEN }}
          EOT
          sudo docker-compose down
          sudo docker-compose up -d --build
          EOF

      - name: Cleanup SSH Key
        if: always()
        run: rm -f lightsail_key.pem
